# Dennis Tobar <dennis.tobar@gmail.com>, 2015. #zanata
# Eduardo Mayorga Téllez <e@mayorgalinux.com>, 2016. #zanata
# Máximo Castañeda Riloba <mcrcctm@gmail.com>, 2016. #zanata
# Omar Berroterán S. <omarberroteranlkf@gmail.com>, 2016. #zanata
# William  Moreno Reyes <williamjmorenor@gmail.com>, 2016. #zanata
# Máximo Castañeda Riloba <mcrcctm@gmail.com>, 2017. #zanata
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2017-04-07 14:44+0200\n"
"PO-Revision-Date: 2017-01-30 02:57-0500\n"
"Last-Translator: Máximo Castañeda Riloba <mcrcctm@gmail.com>\n"
"Language-Team: Spanish\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: es\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"X-Generator: Zanata 3.9.6\n"

#: ../plugins/kickstart.py:58
msgid "Install packages defined in a kickstart file on your system"
msgstr "Instalar los paquetes definidos en el archivo kickstart en su sistema"

#: ../plugins/kickstart.py:63
msgid "kickstart file"
msgstr "archivo kickstart"

#: ../plugins/kickstart.py:81
#, python-format
msgid "file cannot be parsed: %s"
msgstr "no se puede procesar el archivo: %s"

#: ../plugins/kickstart.py:98
#, python-format
msgid "No package %s available."
msgstr "No hay ningún paquete %s disponible."

#: ../plugins/kickstart.py:103
msgid "Nothing to do."
msgstr "Nada por hacer."

#: ../plugins/rpm_conf.py:67
msgid "Adding '{}' to list of handling packages for rpmconf"
msgstr "Agregando '{}'  a la lista de paquetes manejados por rpmconf"

#: ../plugins/rpm_conf.py:73
msgid "rpmconf plugin will not run in non-interactive mode"
msgstr "El complemento rpmconf sólo se ejecuta en modo interactivo"

#: ../plugins/rpm_conf.py:86
msgid "ignoring sys.exit from rpmconf due to missing MERGE variable"
msgstr "se descarta sys.exit de rpmconf al faltar la variable MERGE"

#: ../plugins/rpm_conf.py:90
msgid "ignoring sys.exit from rpmconf due to missing file"
msgstr "se descarta sys.exit de rpmconf por la falta de un archivo"

#: ../plugins/snapper.py:49
#, python-format
msgid "connect to snapperd failed: %s"
msgstr "conexión a snapperd fallida: %s"

#: ../plugins/snapper.py:54
msgid "creating snapshot"
msgstr "creando imagen"

#: ../plugins/snapper.py:59
#, python-format
msgid "created snapshot %d"
msgstr "imagen creada %d"

#: ../plugins/snapper.py:63
#, python-format
msgid "creating snapshot failed: %s"
msgstr "creación de imagen fallida: %s"

#. Translators: This string is only used in unit tests.
#: ../plugins/system_upgrade.py:54
msgid "the color of the sky"
msgstr "el color del cielo"

#: ../plugins/system_upgrade.py:73
msgid "No new kernel packages were found."
msgstr "No se han encontrado nuevos paquetes del kernel."

#: ../plugins/system_upgrade.py:75
msgid "Need a --releasever greater than the current system version."
msgstr "Necesita una --releasever mayor que la versión actual del sistema."

#. Translators: do not change "reboot" here
#: ../plugins/system_upgrade.py:77
msgid ""
"Download complete! Use 'dnf system-upgrade reboot' to start the upgrade."
msgstr ""
"¡Descarga completa! Use 'dnf system-upgrade reboot' para iniciar la "
"actualización."

#: ../plugins/system_upgrade.py:79
msgid "Sorry, you need to use 'download --releasever' instead of '--network'"
msgstr "Use 'download --releasever' en lugar de '--network'"

#: ../plugins/system_upgrade.py:112
msgid "--datadir: File exists"
msgstr "--datadir: Archivo existe"

#: ../plugins/system_upgrade.py:257
msgid "The following boots appear to contain upgrade logs:"
msgstr ""
"Estos arranques parecen contener registros de actualizaciones de sistema:"

#: ../plugins/system_upgrade.py:267
msgid "-- no logs were found --"
msgstr "-- no se encontró ningún registro de actualizaciones --"

#: ../plugins/system_upgrade.py:282
msgid "Cannot find logs with this index."
msgstr "No se encontraron registros con ese índice."

#: ../plugins/system_upgrade.py:305
msgid "Prepare system for upgrade to a new release"
msgstr "Preparar el sistema para una nueva versión"

#: ../plugins/system_upgrade.py:314
msgid "save downloaded data to this location"
msgstr "guardar datos descargados a esta ubicación"

#: ../plugins/system_upgrade.py:317
msgid "keep installed packages if the new release's version is older"
msgstr ""
"mantener los paquetes instalados si la versión del nuevo sistema es anterior"

#: ../plugins/system_upgrade.py:398
msgid "system is not ready for upgrade"
msgstr "el sistema no está listo para la actualización"

#: ../plugins/system_upgrade.py:400
msgid "upgrade is already scheduled"
msgstr "la actualización ya está planificada"

#. Translators: do not change "reboot" here
#: ../plugins/system_upgrade.py:406
msgid "use 'dnf system-upgrade reboot' to begin the upgrade"
msgstr "use 'dnf system-upgrade reboot' para iniciar la actualización"

#: ../plugins/system_upgrade.py:408
msgid "another upgrade tool is running. exiting quietly."
msgstr ""
"existe otra herramienta de actualización en ejecución. Saliendo "
"silenciosamente. "

#: ../plugins/system_upgrade.py:432
msgid "Rebooting to perform upgrade."
msgstr "Reiniciando para proceder a la actualización."

#: ../plugins/system_upgrade.py:459 ../plugins/system_upgrade.py:465
msgid "Starting system upgrade. This will take a while."
msgstr "Iniciando la actualización del sistema. Llevará un rato."

#: ../plugins/system_upgrade.py:496
msgid "Cleaning up downloaded data..."
msgstr "Limpiando los datos descargados..."

#: ../plugins/system_upgrade.py:527
msgid "Download finished."
msgstr "Terminó la descarga."

#: ../plugins/system_upgrade.py:531 ../plugins/system_upgrade.py:532
msgid "Upgrade complete! Cleaning up and rebooting..."
msgstr "¡Actualización completa! Limpiando y reiniciando..."

#: ../plugins/torproxy.py:31
msgid "Disabling torproxy plugin: cannot connect to the Tor network"
msgstr ""
"Desactivando el complemento torproxy: no se puede conectar con la red Tor"

#: ../plugins/tracer.py:75
msgid "For more information run:"
msgstr "Para mayor información ejecute:"

#: ../plugins/tracer.py:102
msgid "Call to Tracer API ended unexpectedly:"
msgstr "La llamada a la API tracer acabó con error:"

#: ../plugins/tracer.py:104
msgid ""
"Please visit https://github.com/FrostyX/tracer/issues and submit the issue. "
"Thank you"
msgstr ""
"Vaya a https://github.com/FrostyX/tracer/issues y envíe un informe de error."

#: ../plugins/tracer.py:106
msgid "We apologize for any inconvenience"
msgstr "Lamentamos cualquier incoveniente"
