# Meskó Balázs <meskobalazs@gmail.com>, 2016. #zanata
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2017-04-07 14:44+0200\n"
"PO-Revision-Date: 2016-12-26 05:34-0500\n"
"Last-Translator: Meskó Balázs <meskobalazs@gmail.com>\n"
"Language-Team: Hungarian\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: hu\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"X-Generator: Zanata 3.9.6\n"

#: ../plugins/kickstart.py:58
msgid "Install packages defined in a kickstart file on your system"
msgstr ""

#: ../plugins/kickstart.py:63
msgid "kickstart file"
msgstr "kickstart fájl"

#: ../plugins/kickstart.py:81
#, python-format
msgid "file cannot be parsed: %s"
msgstr "a fájl nem dolgozható fel: %s"

#: ../plugins/kickstart.py:98
#, python-format
msgid "No package %s available."
msgstr "A(z) %s csomag nem érhető el."

#: ../plugins/kickstart.py:103
msgid "Nothing to do."
msgstr "Nincs tennivaló."

#: ../plugins/rpm_conf.py:67
msgid "Adding '{}' to list of handling packages for rpmconf"
msgstr ""

#: ../plugins/rpm_conf.py:73
msgid "rpmconf plugin will not run in non-interactive mode"
msgstr ""

#: ../plugins/rpm_conf.py:86
msgid "ignoring sys.exit from rpmconf due to missing MERGE variable"
msgstr ""

#: ../plugins/rpm_conf.py:90
msgid "ignoring sys.exit from rpmconf due to missing file"
msgstr ""

#: ../plugins/snapper.py:49
#, python-format
msgid "connect to snapperd failed: %s"
msgstr "a kapcsolódás a snapperd-hez sikertelen: %s"

#: ../plugins/snapper.py:54
msgid "creating snapshot"
msgstr "pillanatfelvétel készítése"

#: ../plugins/snapper.py:59
#, python-format
msgid "created snapshot %d"
msgstr "pillanatfelvétel készítve"

#: ../plugins/snapper.py:63
#, python-format
msgid "creating snapshot failed: %s"
msgstr ""

#. Translators: This string is only used in unit tests.
#: ../plugins/system_upgrade.py:54
msgid "the color of the sky"
msgstr "az égbolt színe"

#: ../plugins/system_upgrade.py:73
msgid "No new kernel packages were found."
msgstr "Nem található új rendszermag csomag."

#: ../plugins/system_upgrade.py:75
msgid "Need a --releasever greater than the current system version."
msgstr ""

#. Translators: do not change "reboot" here
#: ../plugins/system_upgrade.py:77
msgid ""
"Download complete! Use 'dnf system-upgrade reboot' to start the upgrade."
msgstr ""

#: ../plugins/system_upgrade.py:79
msgid "Sorry, you need to use 'download --releasever' instead of '--network'"
msgstr ""

#: ../plugins/system_upgrade.py:112
msgid "--datadir: File exists"
msgstr ""

#: ../plugins/system_upgrade.py:257
msgid "The following boots appear to contain upgrade logs:"
msgstr ""

#: ../plugins/system_upgrade.py:267
msgid "-- no logs were found --"
msgstr ""

#: ../plugins/system_upgrade.py:282
msgid "Cannot find logs with this index."
msgstr ""

#: ../plugins/system_upgrade.py:305
msgid "Prepare system for upgrade to a new release"
msgstr ""

#: ../plugins/system_upgrade.py:314
msgid "save downloaded data to this location"
msgstr ""

#: ../plugins/system_upgrade.py:317
msgid "keep installed packages if the new release's version is older"
msgstr ""

#: ../plugins/system_upgrade.py:398
msgid "system is not ready for upgrade"
msgstr ""

#: ../plugins/system_upgrade.py:400
msgid "upgrade is already scheduled"
msgstr ""

#. Translators: do not change "reboot" here
#: ../plugins/system_upgrade.py:406
msgid "use 'dnf system-upgrade reboot' to begin the upgrade"
msgstr ""

#: ../plugins/system_upgrade.py:408
msgid "another upgrade tool is running. exiting quietly."
msgstr ""

#: ../plugins/system_upgrade.py:432
msgid "Rebooting to perform upgrade."
msgstr ""

#: ../plugins/system_upgrade.py:459 ../plugins/system_upgrade.py:465
msgid "Starting system upgrade. This will take a while."
msgstr ""

#: ../plugins/system_upgrade.py:496
msgid "Cleaning up downloaded data..."
msgstr ""

#: ../plugins/system_upgrade.py:527
msgid "Download finished."
msgstr ""

#: ../plugins/system_upgrade.py:531 ../plugins/system_upgrade.py:532
msgid "Upgrade complete! Cleaning up and rebooting..."
msgstr ""

#: ../plugins/torproxy.py:31
msgid "Disabling torproxy plugin: cannot connect to the Tor network"
msgstr ""

#: ../plugins/tracer.py:75
msgid "For more information run:"
msgstr "További információért futtassa:"

#: ../plugins/tracer.py:102
msgid "Call to Tracer API ended unexpectedly:"
msgstr ""

#: ../plugins/tracer.py:104
msgid ""
"Please visit https://github.com/FrostyX/tracer/issues and submit the issue. "
"Thank you"
msgstr ""

#: ../plugins/tracer.py:106
msgid "We apologize for any inconvenience"
msgstr "Elnézést kérünk a kellemetlenségekért"
