# Luigi Toscano <luigi.toscano@tiscali.it>, 2016. #zanata
# Luigi Toscano <luigi.toscano@tiscali.it>, 2017. #zanata
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2017-04-07 14:44+0200\n"
"PO-Revision-Date: 2017-01-19 11:06-0500\n"
"Last-Translator: Luigi Toscano <luigi.toscano@tiscali.it>\n"
"Language-Team: Italian\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: it\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"X-Generator: Zanata 3.9.6\n"

#: ../plugins/kickstart.py:58
msgid "Install packages defined in a kickstart file on your system"
msgstr "Installa i pacchetti definiti in un file kickstart sul sistema"

#: ../plugins/kickstart.py:63
msgid "kickstart file"
msgstr "File di kickstart"

#: ../plugins/kickstart.py:81
#, python-format
msgid "file cannot be parsed: %s"
msgstr "il file non può essere analizzato: %s"

#: ../plugins/kickstart.py:98
#, python-format
msgid "No package %s available."
msgstr "Nessun pacchetto %s disponibile."

#: ../plugins/kickstart.py:103
msgid "Nothing to do."
msgstr "Niente da fare."

#: ../plugins/rpm_conf.py:67
msgid "Adding '{}' to list of handling packages for rpmconf"
msgstr "Aggiunta di '{}' all'elenco di pacchetti da far gestire a rpmconf"

#: ../plugins/rpm_conf.py:73
msgid "rpmconf plugin will not run in non-interactive mode"
msgstr ""

#: ../plugins/rpm_conf.py:86
msgid "ignoring sys.exit from rpmconf due to missing MERGE variable"
msgstr ""

#: ../plugins/rpm_conf.py:90
msgid "ignoring sys.exit from rpmconf due to missing file"
msgstr ""

#: ../plugins/snapper.py:49
#, python-format
msgid "connect to snapperd failed: %s"
msgstr "connessione a snapperd non riuscita: %s"

#: ../plugins/snapper.py:54
msgid "creating snapshot"
msgstr ""

#: ../plugins/snapper.py:59
#, python-format
msgid "created snapshot %d"
msgstr ""

#: ../plugins/snapper.py:63
#, python-format
msgid "creating snapshot failed: %s"
msgstr ""

#. Translators: This string is only used in unit tests.
#: ../plugins/system_upgrade.py:54
msgid "the color of the sky"
msgstr "il colore del cielo"

#: ../plugins/system_upgrade.py:73
msgid "No new kernel packages were found."
msgstr "Nessun nuovo pacchetto di kernel è stato trovato."

#: ../plugins/system_upgrade.py:75
msgid "Need a --releasever greater than the current system version."
msgstr ""
"Richiesto un valore di --releasever maggiore della versione attuale del "
"sistema."

#. Translators: do not change "reboot" here
#: ../plugins/system_upgrade.py:77
msgid ""
"Download complete! Use 'dnf system-upgrade reboot' to start the upgrade."
msgstr ""
"Scaricamento completato! Usare 'dnf system-upgrade reboot' per avviare "
"l'aggiornamento."

#: ../plugins/system_upgrade.py:79
msgid "Sorry, you need to use 'download --releasever' instead of '--network'"
msgstr "Bisogna usare l'opzione 'download --releasever' invece di '--network'"

#: ../plugins/system_upgrade.py:112
msgid "--datadir: File exists"
msgstr "--datadir: il file esiste"

#: ../plugins/system_upgrade.py:257
msgid "The following boots appear to contain upgrade logs:"
msgstr ""
"I seguenti precedenti avvii del sistema sembrano contenere dei log di "
"aggiornamenti:"

#: ../plugins/system_upgrade.py:267
msgid "-- no logs were found --"
msgstr "-- nessun log è stato trovato --"

#: ../plugins/system_upgrade.py:282
msgid "Cannot find logs with this index."
msgstr ""

#: ../plugins/system_upgrade.py:305
msgid "Prepare system for upgrade to a new release"
msgstr ""

#: ../plugins/system_upgrade.py:314
msgid "save downloaded data to this location"
msgstr ""

#: ../plugins/system_upgrade.py:317
msgid "keep installed packages if the new release's version is older"
msgstr ""

#: ../plugins/system_upgrade.py:398
msgid "system is not ready for upgrade"
msgstr ""

#: ../plugins/system_upgrade.py:400
msgid "upgrade is already scheduled"
msgstr ""

#. Translators: do not change "reboot" here
#: ../plugins/system_upgrade.py:406
msgid "use 'dnf system-upgrade reboot' to begin the upgrade"
msgstr ""

#: ../plugins/system_upgrade.py:408
msgid "another upgrade tool is running. exiting quietly."
msgstr ""

#: ../plugins/system_upgrade.py:432
msgid "Rebooting to perform upgrade."
msgstr "Riavvio per effettuare l'aggiornamento."

#: ../plugins/system_upgrade.py:459 ../plugins/system_upgrade.py:465
msgid "Starting system upgrade. This will take a while."
msgstr "Avvio dell'aggiornamento del sistema. Ci vorrà un po'."

#: ../plugins/system_upgrade.py:496
msgid "Cleaning up downloaded data..."
msgstr "Pulizia dei dati scaricati..."

#: ../plugins/system_upgrade.py:527
msgid "Download finished."
msgstr "Scaricamento completato."

#: ../plugins/system_upgrade.py:531 ../plugins/system_upgrade.py:532
msgid "Upgrade complete! Cleaning up and rebooting..."
msgstr "Aggiornamento completato! Pulizia e riavvio in corso..."

#: ../plugins/torproxy.py:31
msgid "Disabling torproxy plugin: cannot connect to the Tor network"
msgstr ""

#: ../plugins/tracer.py:75
msgid "For more information run:"
msgstr "Per maggiori informazioni eseguire:"

#: ../plugins/tracer.py:102
msgid "Call to Tracer API ended unexpectedly:"
msgstr ""

#: ../plugins/tracer.py:104
msgid ""
"Please visit https://github.com/FrostyX/tracer/issues and submit the issue. "
"Thank you"
msgstr ""

#: ../plugins/tracer.py:106
msgid "We apologize for any inconvenience"
msgstr "Ci scusiamo per i disagi"
